version: '3'

services:
  laravel: 
    image: docker_php:step5
    build: . 
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=sample
      - DB_USERNAME=foo
      - DB_PASSWORD=bar
    
    volumes:
      - ./example-app:/app/src

    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - laravel:/var/lib/mysql
    
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=sample
      - MYSQL_USER=foo
      - MYSQL_PASSWORD=bar
    


    